### ISSUE TITLE
Mute damage taken sound

### ISSUE THREAD

**Issue by luizpheelipe** [RDieleman/runelite-pickpocket-helper#2]
Not really a problem but since I didn't saw any direct contact I will just use here.

Is there a way to mute the sound from when you take damage?
I think that are 2-3 different sound for when you take damage, I tried to disable using ID but I couldn't find the ID sound for when you take damage.

I think it would be very good for the plugin.
Anyway I appreciate your plugin a lot, made pickpocketing much more fun especially with the girl that says when my hitpoints are low :3

**Comment by RDieleman** [comment]
@luizpheelipe I'm glad you're enjoying the plugin!

Damage sounds should be muted if you enable the `Mute Fail Sounds` setting under `Sounds`.

**Comment by luizpheelipe** [comment]
> 



> @luizpheelipe I'm glad you're enjoying the plugin!
> 
> Damage sounds should be muted if you enable the `Mute Fail Sounds` setting under `Sounds`.

It didn't mute the damage taken, at least not for me... but using the **visual sounds plugin** I found the ID for female to be 509 an 510 using the list ID from wiki.
I just added the IDs on the **Annoyance Mute Plugins** ;3
Either way is just a minor thing

**Comment by RDieleman** [comment]
Ooh, interesting. Didn't know female and male damage sounds were different. I'll make sure to include them.

Thanks for letting me know!
