### ISSUE TITLE
Please also add tracking for the number of stalls you pickpocket

### ISSUE THREAD

**Issue by Bart123456789** [RDieleman/runelite-pickpocket-helper#5]
Dear creator,

It would be nice to also see the number of stalls you have pickpocket and see amount of stalls you can pickpocket a hour.
As this is one of the fastest ways to get the pet it would be nice to also track the number of pockets you already did.

Greetings,

Bart

**Comment by RDieleman** [comment]
Sorry, this would be a bit out of scope for the plugin.
